#!/usr/bin/env python3
"""Build the PyroSight demo navigation module (camera/nav).

    python3 camera/nav/build_nav.py

1. Compiles the device's navigation code (core/src/ps_nav.c, ps_config.c,
   ps_alerts.c) plus the C API shim nav/src/nav_api.c to WebAssembly (zig cc,
   wasm32-wasi, MVP feature set) and converts it to plain JavaScript with
   binaryen's wasm2js (the host page may forbid WebAssembly; nothing here uses it).
2. Concatenates that with the JavaScript parts into ONE classic script:
       dist/ps_nav.js     defines globalThis.PSNav (and module.exports in node)
3. Inlines it into the standalone test page:
       demo.html          self-contained, no network (fragment: no doctype/html/head/body)
       dist/nav_demo.html the same with a doctype + viewport wrapper, to open directly

Needs: `python3 -m pip install ziglang`, and wasm2js (binaryen; set WASM2JS or
let it be found in node_modules/binaryen/bin or the scratch jsbuild folder).
Checks: no network APIs or URLs, no eval / Function / WebAssembly / Worker /
import(), no "</script" inside the script.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

NAV = os.path.dirname(os.path.abspath(__file__))
CAMERA = os.path.dirname(NAV)
ROOT = os.path.dirname(CAMERA)
CORE_SRC = [os.path.join(ROOT, "core", "src", f) for f in ("ps_nav.c", "ps_config.c", "ps_alerts.c")]
SHIM = os.path.join(NAV, "src", "nav_api.c")
JS_PARTS = ["core.js", "stepdetect.js", "sensors.js", "walker.js", "navigator.js", "render.js"]
FORBIDDEN = [
    (r"https?://", "URL"), (r"\bfetch\s*\(", "fetch"), (r"XMLHttpRequest", "XHR"), (r"WebSocket", "WebSocket"),
    (r"\bWorker\s*\(", "Worker"), (r"\beval\s*\(", "eval"), (r"new\s+Function\b", "Function"),
    (r"\bimport\s*\(", "import()"), (r"WebAssembly", "WebAssembly"), (r"</script", "</script"),
    (r"\balert\s*\(", "alert()"), (r"\bconfirm\s*\(", "confirm()"), (r"\bprompt\s*\(", "prompt()"),
    (r"sendBeacon", "sendBeacon"), (r"EventSource", "EventSource"),
]


def find_wasm2js():
    cand = os.environ.get("WASM2JS") or shutil.which("wasm2js")
    if cand:
        return cand
    for base in (CAMERA, ROOT, os.path.join(ROOT, "sim", "web"),
                 "/tmp/claude-0/-home-claude/069cc723-8434-5b03-8db8-df5ff0accd4e/scratchpad/jsbuild"):
        p = os.path.join(base, "node_modules", "binaryen", "bin", "wasm2js")
        if os.path.exists(p):
            return p
    sys.exit("wasm2js not found: `npm install binaryen` and set WASM2JS=/path/to/wasm2js")


def build_core_js(tmp):
    wasm = os.path.join(tmp, "nav.wasm")
    cmd = [sys.executable, "-m", "ziglang", "cc", "-target", "wasm32-wasi", "-O2", "-mexec-model=reactor", "-mcpu=mvp",
           "-I" + os.path.join(ROOT, "core", "include"), "-fvisibility=hidden",
           "-Wl,--export-dynamic", "-Wl,--strip-all", "-Wl,--initial-memory=131072", "-Wl,-z,stack-size=32768",
           *CORE_SRC, SHIM, "-o", wasm, "-lm"]
    subprocess.run(cmd, check=True)
    js_path = os.path.join(tmp, "nav.mjs")
    subprocess.run([find_wasm2js(), wasm, "-O2", "-o", js_path], check=True)
    js = open(js_path).read()
    js = re.sub(r"^export var .*$\n?", "", js, flags=re.M)
    head = js.split("function asmFunc")[0]
    if "import " in head:
        sys.exit("unexpected imports in wasm2js output")
    if "var retasmFunc = asmFunc(" not in js:
        sys.exit("unexpected wasm2js output layout")
    return (
        "/* Generated by camera/nav/build_nav.py: core/src/ps_nav.c + ps_config.c + ps_alerts.c +\n"
        " * camera/nav/src/nav_api.c, compiled with zig (wasm32, MVP) and converted to JavaScript by\n"
        " * binaryen wasm2js. Every call of PSNav._createAsm() makes a new, independent instance. */\n"
        "(function (root) {\n'use strict';\nvar PSNav = root.PSNav = root.PSNav || {};\n"
        "PSNav._createAsm = function () {\n" + js + "\nreturn retasmFunc;\n};\n"
        "})(typeof globalThis !== 'undefined' ? globalThis : this);\n"
    )


def check(name, text):
    bad = [label for pat, label in FORBIDDEN if re.search(pat, text)]
    if bad:
        sys.exit("%s contains forbidden constructs: %s" % (name, ", ".join(bad)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(NAV, "dist"))
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        core_js = build_core_js(tmp)
    parts = [core_js]
    for p in JS_PARTS:
        parts.append("/* ---- camera/nav/src/%s ---- */\n" % p + open(os.path.join(NAV, "src", p)).read())
    bundle = (
        "/*! PyroSight demo navigation (camera/nav). Built by build_nav.py; edit src/, not this file.\n"
        " * Defines globalThis.PSNav. See camera/nav/README.md for the interface. */\n"
        + "\n".join(parts)
        + "\nif (typeof module === 'object' && module && module.exports) module.exports = globalThis.PSNav;\n"
    )
    check("ps_nav.js", bundle)
    out_js = os.path.join(args.out, "ps_nav.js")
    with open(out_js, "w") as f:
        f.write(bundle)

    tpl = open(os.path.join(NAV, "src", "demo.src.html")).read()
    if "/*@@PS_NAV_JS@@*/" not in tpl:
        sys.exit("demo template marker missing")
    page = tpl.replace("/*@@PS_NAV_JS@@*/", bundle)
    page_scripts = "\n".join(re.findall(r"<script>(.*?)</script>", tpl, flags=re.S))
    check("demo page script", page_scripts.replace("/*@@PS_NAV_JS@@*/", ""))
    if re.search(r"<(link|img|iframe)\b[^>]*(src|href)=", page) or re.search(r"<script[^>]+src=", page):
        sys.exit("demo page references external resources")
    if "<title>PyroSight Navigation Demo</title>" not in page:
        sys.exit("demo page title missing")
    demo = os.path.join(NAV, "demo.html")
    with open(demo, "w") as f:
        f.write(page)
    full = os.path.join(args.out, "nav_demo.html")
    with open(full, "w") as f:
        f.write('<!doctype html>\n<html lang="en">\n<meta charset="utf-8">\n'
                '<meta name="viewport" content="width=device-width, initial-scale=1">\n' + page + "\n</html>\n")
    for p in (out_js, demo, full):
        print("wrote %s (%.0f KB)" % (os.path.relpath(p, ROOT), os.path.getsize(p) / 1024))


if __name__ == "__main__":
    main()
