#!/usr/bin/env python3
"""Rebuild the people/face models and write dist/people_assets.js, the one
file the PyroSight Camera page inlines (after tf.min.js, oplist.js, people.js):

    globalThis.PS_PEOPLE_ASSETS = {
      person: {json, weightsB64},   // repack_cocossd.py output (COCO-SSD, person head, uint8)
      face:   {json, weightsB64},   // export_oplist.py output (BlazeFace short range, float16)
      info:   {...}                 // sizes, sources, licences
    }

    python3 build_assets.py            # rebuild models + bundle
    python3 build_assets.py --no-build # bundle existing models/ only
    python3 build_assets.py --demo     # also write dist/people_demo.html (camera test page)
"""
import argparse
import base64
import hashlib
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CAMERA = os.path.dirname(HERE)
TFJS = os.path.join(CAMERA, 'node_modules/@tensorflow/tfjs/dist/tf.min.js')


def run(cmd):
    print('+', ' '.join(cmd))
    subprocess.check_call(cmd, cwd=HERE)


def asset(json_path, bin_path):
    doc = json.load(open(json_path))
    blob = open(bin_path, 'rb').read()
    return doc, blob


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-build', action='store_true')
    ap.add_argument('--person-weights', default='uint8', choices=['uint8', 'float16', 'float32'])
    ap.add_argument('--face-weights', default='float16', choices=['uint8', 'float16', 'float32'])
    ap.add_argument('--keep-classes', default='person')
    ap.add_argument('--demo', action='store_true')
    a = ap.parse_args()
    os.makedirs(os.path.join(HERE, 'models'), exist_ok=True)
    os.makedirs(os.path.join(HERE, 'dist'), exist_ok=True)
    person_prefix = os.path.join(HERE, 'models/cocossd_person')
    face_prefix = os.path.join(HERE, 'models/blazeface_%s' % a.face_weights)
    if not a.no_build:
        run([sys.executable, 'repack_cocossd.py', '--src', os.path.join(CAMERA, 'assets/cocossd'),
             '--out', person_prefix, '--weights', a.person_weights, '--keep-classes', a.keep_classes])
        run([sys.executable, 'export_oplist.py', os.path.join(CAMERA, 'assets/blazeface/blaze_face_short_range.tflite'),
             '-o', face_prefix, '--weights', a.face_weights])
    pdoc, pblob = asset(person_prefix + '.json', person_prefix + '.weights.bin')
    fdoc, fblob = asset(face_prefix + '.oplist.json', face_prefix + '.weights.bin')
    info = {
        'person': {'model': 'COCO-SSD lite_mobilenet_v2 (TF.js), re-packed', 'licence': 'Apache-2.0',
                   'classes': [c['name'] for c in pdoc['classes']], 'storage': pdoc['meta']['weight_storage'],
                   'weights_bytes': len(pblob), 'sha256': hashlib.sha256(pblob).hexdigest()},
        'face': {'model': 'MediaPipe BlazeFace short range (TFLite) -> op list', 'licence': 'Apache-2.0',
                 'storage': fdoc['meta']['weight_storage'], 'weights_bytes': len(fblob),
                 'sha256': hashlib.sha256(fblob).hexdigest()},
    }
    out = os.path.join(HERE, 'dist/people_assets.js')
    with open(out, 'w') as f:
        f.write('/* PyroSight Camera people/face models. Generated by runtime/build_assets.py - do not edit.\n'
                ' * COCO-SSD (tfjs-models, Apache-2.0) and MediaPipe BlazeFace short range (Apache-2.0);\n'
                ' * see runtime/LICENSES.md. */\n')
        f.write('globalThis.PS_PEOPLE_ASSETS = {\n')
        f.write('person: {json: %s,\nweightsB64: "%s"},\n' % (json.dumps(pdoc, separators=(',', ':')),
                                                             base64.b64encode(pblob).decode()))
        f.write('face: {json: %s,\nweightsB64: "%s"},\n' % (json.dumps(fdoc, separators=(',', ':')),
                                                           base64.b64encode(fblob).decode()))
        f.write('info: %s\n};\n' % json.dumps(info))
    sz = os.path.getsize(out)
    print('wrote %s (%.2f MB): person %d B weights, face %d B weights' % (out, sz / 1e6, len(pblob), len(fblob)))
    if a.demo:
        write_demo()


def write_demo():
    """Minimal self-contained camera test page (all scripts inline)."""
    parts = {n: open(p).read() for n, p in [('tf', TFJS), ('oplist', os.path.join(HERE, 'oplist.js')),
                                             ('people', os.path.join(HERE, 'people.js')),
                                             ('assets', os.path.join(HERE, 'dist/people_assets.js'))]}
    for k, v in parts.items():
        if '</script' in v.lower():
            parts[k] = v.replace('</script', '<\\/script').replace('</SCRIPT', '<\\/SCRIPT')
    html = DEMO_HTML
    for k in ('tf', 'oplist', 'people', 'assets'):
        html = html.replace('/*%%%s%%*/' % k.upper(), parts[k])
    out = os.path.join(HERE, 'dist/people_demo.html')
    open(out, 'w').write(html)
    print('wrote %s (%.2f MB)' % (out, os.path.getsize(out) / 1e6))


DEMO_HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>People Detector Test</title>
<style>
:root { --bg: #0b0d10; --fg: #e8e8e8; --muted: #9aa0a6; }
@media (prefers-color-scheme: light) { :root:not([data-theme="dark"]) { --bg: #f4f4f4; --fg: #111; --muted: #555; } }
body { margin: 0; background: var(--bg); color: var(--fg); font: 14px/1.4 system-ui, sans-serif; }
main { max-width: 960px; margin: 0 auto; padding: 16px; }
#wrap { position: relative; width: 100%; background: #000; }
video, canvas { width: 100%; display: block; }
#ov { position: absolute; left: 0; top: 0; }
#stat { color: var(--muted); font-family: ui-monospace, monospace; white-space: pre-wrap; }
button { font: inherit; padding: 6px 14px; }
</style></head><body><main>
<p>Runtime test page for runtime/people.js. Video stays on this device: nothing is uploaded.</p>
<p><button id="go">Start camera</button></p>
<div id="wrap"><video id="v" playsinline muted></video><canvas id="ov"></canvas></div>
<div id="stat">loading models...</div>
</main>
<script>/*%TF%*/</script>
<script>/*%OPLIST%*/</script>
<script>/*%PEOPLE%*/</script>
<script>/*%ASSETS%*/</script>
<script>
(async () => {
  const stat = document.getElementById('stat');
  const v = document.getElementById('v'), ov = document.getElementById('ov');
  const q = new URLSearchParams(location.search);
  const backend = await PSPeople.setupBackend(tf, { prefer: q.get('backend') || undefined,
    allowSoftwareWebGL: q.get('swgl') === '1' });
  const info = await PSPeople.init(tf, PS_PEOPLE_ASSETS);
  window.__ps = { backend, info, frames: 0, last: null, tensors: [], ms: [], labels: [] };
  stat.textContent = 'backend ' + backend + ', models ready in ' + Math.round(info.loadMs) + ' ms';
  async function loop() {
    if (v.readyState >= 2) {
      const r = await PSPeople.detect(v);
      ov.width = v.videoWidth; ov.height = v.videoHeight;
      const g = ov.getContext('2d');
      g.clearRect(0, 0, ov.width, ov.height);
      g.lineWidth = 3; g.strokeStyle = '#FFFFFF'; g.fillStyle = '#FFFFFF'; g.font = '16px monospace';
      for (const d of r.display) {
        g.strokeRect(d.x * ov.width, d.y * ov.height, d.w * ov.width, d.h * ov.height);
        g.fillText((d.label || '') + ' ' + d.src, d.x * ov.width + 4, Math.max(16, d.y * ov.height - 4));
      }
      window.__ps.frames++; window.__ps.last = r; window.__ps.tensors.push(tf.memory().numTensors);
      window.__ps.ms.push(r.ms); window.__ps.labels.push(r.display.map((d) => d.src + ':' + d.label).join(' '));
      stat.textContent = 'backend ' + backend + ' | ' + r.display.length + ' people | ' +
        Math.round(r.ms.total) + ' ms/frame | tensors ' + tf.memory().numTensors;
    }
    requestAnimationFrame(loop);
  }
  document.getElementById('go').onclick = async () => {
    v.srcObject = await navigator.mediaDevices.getUserMedia({ video: { width: 640, height: 480 }, audio: false });
    await v.play();
    loop();
  };
  window.__ps.ready = true;
})().catch((e) => { document.getElementById('stat').textContent = 'error: ' + e; window.__ps = { error: String(e) }; });
</script></body></html>
'''

if __name__ == '__main__':
    main()
