/*
 * PyroSight demo navigation: JavaScript face of the device's navigation code.
 *
 * PSNav._createAsm() (generated by build_nav.py from core/src/ps_nav.c,
 * ps_config.c, ps_alerts.c and nav/src/nav_api.c via zig + wasm2js) returns a
 * fresh, independent instance of the C code as plain JavaScript: no
 * wasm at run time, no eval, no network. PSNav.Core wraps one instance.
 *
 * Conventions (same as the device):
 *   - yaw in radians, counter-clockwise seen from above: turning LEFT increases yaw;
 *   - entry frame: origin at the marked doorway, +x = the heading when entry was
 *     marked, +y = to the left of it; metres;
 *   - relative bearings in degrees, + = to the LEFT of where the wearer faces;
 *   - time: integer milliseconds, monotonic (wrapped to uint32 by the C code).
 */
(function (root) {
  'use strict';
  const PSNav = root.PSNav = root.PSNav || {};

  /* Layout of api_state() in nav_api.c. */
  const S = {
    STATE: 0, VALID: 1, ROUTE_BRG: 2, HOME_BRG: 3, ROUTE_DIST: 4, HOME_DIST: 5, SIGMA: 6, CONF: 7,
    EXIT_NEXT: 8, LEVEL: 9, X: 10, Y: 11, YAW: 12, WALKED: 13, STEPS: 14, NCRUMBS: 15, TARGET: 16,
    HSIGMA: 17, TURNS: 18, ROUTE_PHRASE: 19, HOME_PHRASE: 20, UNTRACKED: 21, ACCEL_LP: 22, CROSS: 23,
    HAVE_YAW: 24, YAW_RAW: 25,
  };
  /* api_set_cfg / api_get_cfg keys. */
  const CFG = {
    stepLengthM: 0, headingSnap: 1, imuTimeoutMs: 2, gyroDriftDegPerMin: 3, navConfScaleM: 4,
    waypointReachedM: 5, breadcrumbSpacingM: 6, navConfWarn: 7, navConfUnreliable: 8, cameraHeightM: 9,
  };
  /* ps_phrase_t (core/include/pyrosight/ps_alerts.h). */
  const PHRASE = {
    NONE: 0, WAY_OUT_IS: 1, DIR_AHEAD: 2, DIR_AHEAD_LEFT: 3, DIR_LEFT: 4, DIR_BEHIND_LEFT: 5,
    DIR_BEHIND: 6, DIR_BEHIND_RIGHT: 7, DIR_RIGHT: 8, DIR_AHEAD_RIGHT: 9, NAV_UNRELIABLE: 10,
    FOLLOW_HOSE: 11, NAV_RECOVERED: 12, PERSON: 13, FIRE: 14, CAMERA_LOST: 15, CAMERA_RESTORED: 16,
    MOTION_LOST: 17, ENTRY_MARKED: 18, AT_EXIT: 19, BATTERY_LOW: 20, BATTERY_CRITICAL: 21,
  };
  const PHRASE_NAMES = Object.keys(PHRASE);
  /* Direction words, same eight sectors as ps_direction_phrase() (45 degrees each, + = left). */
  const DIR_WORDS = ['ahead', 'ahead-left', 'left', 'behind-left', 'behind', 'behind-right', 'right', 'ahead-right'];
  const STATES = ['idle', 'tracking', 'lost'];
  const LEVELS = ['GOOD', 'DEGRADED', 'UNRELIABLE'];

  /** Direction word for a relative bearing (deg, + = left); identical sectors to the device. */
  function directionWord(bearingDeg) {
    // ps_direction_phrase: s = lroundf(b / 45) mod 8 (lroundf rounds half away from zero).
    const q = bearingDeg / 45;
    let s = q >= 0 ? Math.floor(q + 0.5) : -Math.floor(-q + 0.5);
    s = ((s % 8) + 8) % 8;
    return DIR_WORDS[s];
  }

  function Core() {
    if (typeof PSNav._createAsm !== 'function') throw new Error('PSNav core not built (run camera/nav/build_nav.py)');
    const ex = PSNav._createAsm();
    if (ex._initialize) ex._initialize();
    ex.api_init();
    this.ex = ex;
    // Phrase texts straight from the C table (ps_phrase_text).
    this.phraseText = [];
    const n = ex.api_phrase_count();
    for (let i = 0; i < n; i++) this.phraseText.push(this._cstr(ex.api_phrase_text(i)));
  }

  Core.prototype._cstr = function (ptr) {
    const u = new Uint8Array(this.ex.memory.buffer, ptr, 256);
    let s = '';
    for (let i = 0; i < u.length && u[i]; i++) s += String.fromCharCode(u[i]);
    return s;
  };
  Core.prototype._f32 = function (ptr, n) { return new Float32Array(this.ex.memory.buffer, ptr, n); };

  Core.prototype.setCfg = function (name, v) {
    if (!(name in CFG)) throw new Error('unknown nav config ' + name);
    this.ex.api_set_cfg(CFG[name], typeof v === 'boolean' ? (v ? 1 : 0) : v);
  };
  Core.prototype.getCfg = function (name) { return this.ex.api_get_cfg(CFG[name]); };
  Core.prototype.markEntry = function (t) { this.ex.api_mark_entry(t >>> 0); };
  Core.prototype.reset = function () { this.ex.api_reset(); };
  Core.prototype.onYaw = function (yawRad, t) { this.ex.api_on_yaw(yawRad, t >>> 0); };
  Core.prototype.onStep = function (t) { this.ex.api_on_step(t >>> 0); };
  Core.prototype.onAccel = function (mag, t) { this.ex.api_on_accel(mag, t >>> 0); };
  Core.prototype.tick = function (t) { this.ex.api_tick(t >>> 0); };
  Core.prototype.whereOut = function (t) { this.ex.api_where_out(t >>> 0); };
  Core.prototype.quatToYaw = function (w, x, y, z) { return this.ex.api_quat_to_yaw(w, x, y, z); };
  Core.prototype.directionPhrase = function (b) { return this.ex.api_direction_phrase(b); };

  /** Raw state array copy (layout S). */
  Core.prototype.raw = function () { return Array.from(this._f32(this.ex.api_state(), 26)); };

  /** Breadcrumbs in the entry frame: [{x, y, headingSigma}], [0] = the doorway. */
  Core.prototype.crumbs = function () {
    const n = this.ex.api_n_crumbs(), a = this._f32(this.ex.api_crumbs(), n * 3), out = [];
    for (let i = 0; i < n; i++) out.push({ x: a[3 * i], y: a[3 * i + 1], headingSigma: a[3 * i + 2] });
    return out;
  };

  /** Spoken alerts queued by the device logic since the last call, highest priority first. */
  Core.prototype.popAlerts = function () {
    const out = [];
    for (let guard = 0; guard < 16; guard++) {
      const n = this.ex.api_alert_pop();
      if (!n) break;
      const b = new Int32Array(this.ex.memory.buffer, this.ex.api_alert_buf(), 6);
      const parts = Array.from(b.subarray(0, n));
      out.push({
        parts, names: parts.map((p) => PHRASE_NAMES[p] || String(p)), prio: b[4], t: b[5] >>> 0,
        text: parts.map((p) => this.phraseText[p]).join(' '),
      });
    }
    return out;
  };

  /**
   * Guidance snapshot (pure data). Same fields as ps_nav_guidance_t plus the
   * state, the alert level (device hysteresis), direction words and phrases.
   */
  Core.prototype.guidance = function () {
    const s = this._f32(this.ex.api_state(), 26);
    const state = STATES[s[S.STATE]] || 'idle', levelId = s[S.LEVEL] | 0, valid = s[S.VALID] > 0.5;
    const level = LEVELS[levelId];
    const rb = s[S.ROUTE_BRG], hb = s[S.HOME_BRG];
    const routePhrase = s[S.ROUTE_PHRASE] | 0, homePhrase = s[S.HOME_PHRASE] | 0;
    const unreliable = valid && levelId === 2;
    const phraseIds = !valid ? [] : unreliable ? [PHRASE.NAV_UNRELIABLE, PHRASE.FOLLOW_HOSE] : [PHRASE.WAY_OUT_IS, routePhrase];
    return {
      state, valid,
      routeBearingDeg: rb, homeBearingDeg: hb,
      routeDistM: s[S.ROUTE_DIST], homeDistM: s[S.HOME_DIST],
      posSigmaM: s[S.SIGMA], confidence: s[S.CONF],
      level, levelId, exitIsNext: s[S.EXIT_NEXT] > 0.5,
      word: valid ? DIR_WORDS[routePhrase - PHRASE.DIR_AHEAD] : '',
      homeWord: valid ? DIR_WORDS[homePhrase - PHRASE.DIR_AHEAD] : '',
      phraseIds, phrase: phraseIds.map((p) => this.phraseText[p]).join(' '),
      followHose: unreliable,
      atExit: valid && s[S.ROUTE_DIST] < 1.0,   // the device ring shows "EXIT" below 1 m
      pos: { x: s[S.X], y: s[S.Y] }, yaw: s[S.YAW],
      distWalkedM: s[S.WALKED], steps: s[S.STEPS] | 0, turns: s[S.TURNS] | 0,
      nCrumbs: s[S.NCRUMBS] | 0, returnTarget: s[S.TARGET] | 0,
      headingSigmaDeg: s[S.HSIGMA] * 180 / Math.PI, untrackedS: s[S.UNTRACKED], accelLp: s[S.ACCEL_LP],
    };
  };

  PSNav.Core = Core;
  PSNav.S = S;
  PSNav.CFG = CFG;
  PSNav.PHRASE = PHRASE;
  PSNav.DIR_WORDS = DIR_WORDS;
  PSNav.LEVELS = LEVELS;
  PSNav.directionWord = directionWord;
  PSNav.wrapPi = function (a) { while (a > Math.PI) a -= 2 * Math.PI; while (a <= -Math.PI) a += 2 * Math.PI; return a; };
  PSNav.wrap180 = function (a) { a = ((a + 180) % 360 + 360) % 360 - 180; return a === -180 ? 180 : a; };
})(typeof globalThis !== 'undefined' ? globalThis : this);
